FROM kalilinux/kali-rolling
RUN apt update
RUN apt install -y git
RUN useradd -m aidden
RUN git clone https://github.com/aidden-laoch/sabre.git /home/aidden/sabre
RUN chmod +x /home/aidden/sabre/Sabre-TOC/install.sh
RUN bash -c /home/aidden/sabre/Sabre-TOC/install.sh