FROM kalilinux/kali-rolling
RUN apt update
RUN apt install -y git
RUN useradd -m aidden
RUN git clone https://github.com/aidden-laoch/sabre.git /opt
RUN chmod +x /opt/sabre/Sabre-TOC/install.sh
RUN bash -c /opt/sabre/Sabre-TOC/install.sh
ENTRYPOINT ['sabre']