#!/usr/bin/python3

import sys
import subprocess
import argparse

parser = argparse.ArgumentParser(description='Control Sabre Tactical Operations Center (TOC).')
parser.add_argument('-s', '--start', required=False, help='Start Sabre-TOC Services')
parser.add_argument('-k', '--stop', required=False, help='Stop Sabre-TOC Services')
parser.add_argument('-c', '--status', required=False, help='Check Sabre-TOC Services')
args = parser.parse_args()

if args.start:
	loggingClientsStart = subprocess.check_output('', shell=True)
	loggingClientsStart = subprocess.check_output('', shell=True)

